# ============================================================
# Exercise: Billing with Command-Line Parameters (argparse)
# ------------------------------------------------------------
# Problem:
#   Write a script that accepts item prices from the command line and
#   optional percentage values for discount and tax, then prints a bill.

#   Required:
#     prices (one or more positional floats)
#   Optional:
#     --discount (percentage, float, default 0)
#     --tax      (percentage, float, default 0)

#   Compute:
#     subtotal        = sum(prices)
#     discount_amount = subtotal * (discount / 100)
#     after_discount  = subtotal - discount_amount
#     tax_amount      = after_discount * (tax / 100)
#     total           = after_discount + tax_amount

#   Output a neat breakdown with 2-decimal formatting.

# How to run (examples):
#   python 07_command_line_args.py 100 250.5 49.99 --discount 10 --tax 18
#   python 07_command_line_args.py 799 --tax 5
#   python 07_command_line_args.py 199 299 399 499

# Short notes:
#   - Command-line args are read from sys.argv. argparse helps parse & validate.
#   - Use positional args for required values; flags (like --tax) for optional.
#   - Run "python bill.py -h" to see auto-generated help.
# ============================================================

import argparse

parser = argparse.ArgumentParser(
    description="Compute a bill from item prices with optional discount and tax."
)

# Positional: one or more prices
parser.add_argument(
    "prices",
    nargs="+",
    type=float,
    help="Item prices (one or more numbers, e.g., 100 249.99 59.5)",
)

# Optional flags
parser.add_argument(
    "--discount", "-d",
    type=float,
    default=0.0,
    help="Discount percentage to apply (e.g., 10 for 10%%). Default: 0",
)
parser.add_argument(
    "--tax", "-t",
    type=float,
    default=0.0,
    help="Tax percentage to apply after discount (e.g., 18 for 18%%). Default: 0",
)

args = parser.parse_args()

# Calculations
subtotal = sum(args.prices)
discount_amount = subtotal * (args.discount / 100.0)
after_discount = subtotal - discount_amount
tax_amount = after_discount * (args.tax / 100.0)
total = after_discount + tax_amount

# Output
print("\n--- BILL ---")
print(f"Items:            {', '.join(f'{p:.2f}' for p in args.prices)}")
print(f"Subtotal:         ₹{subtotal:.2f}")
print(f"Discount ({args.discount:.2f}%): -₹{discount_amount:.2f}")
print(f"After discount:   ₹{after_discount:.2f}")
print(f"Tax ({args.tax:.2f}%):        +₹{tax_amount:.2f}")
print("-" * 32)
print(f"Total:            ₹{total:.2f}")

# Tip: Try `python bill.py -h` to see the help message generated by argparse.
